# Assessment: Part 2 - Optimisation
<br>

## Task: Optimise a timetable so that session is scheduled once per week in such a way that timetable constraints are minimised. 
<br>

### Relevant constraints for this assessment are: 

- A session cannot be scheduled for a time when any of its students or staff are in another session (concurrence constraints). The sessions for a module that clash are shown in the data file.
- A lab session cannot occur in the week before its corresponding lecture has taken place (precedence constraints).
<br>
<br>

### Packages needed:

- pandas
- sklearn
- numpy
- matplotlib

### 2.1 – Generation of random solutions

#### Importing libraries

In [5]:
import numpy as np
import random
import random
import time
import math
import matplotlib.pyplot as plt

In [11]:
file = "./Modules.txt"

# Load the list of modules in to an array to read only permissions
modules_file = open(file, "r")
modules = [] # List that will hold the modules
for line in modules_file:
    module = line.strip('\n')
    modules.append(module)

#close the file
modules_file.close()

Index(['MOD001|Zacharias Karstensen|2|MOD002,MOD003,MOD004,MOD005,MOD006,MOD007,MOD008,MOD009,MOD010,MOD013'], dtype='object')

In [8]:
def onemax(x):
  return x.sum()

D = 17
def generate_binary(D):
  ## Generate a array of D bits
  return np.random.randint(0, 11, D)

for i in range(5):
  x = generate_binary(10)
  y = onemax(x)

  print(f"{x} + {y}")


def binary_mutation(parent):
  idx = np.random.randint(parent.shape[0])

  child = parent.copy()
  child[idx] = abs(parent[idx] - 1)

  return child

def greater_than_equal(a, b):
  return a >= b

def hillclimber(Niter, problem, D, generate_binary, mutation, comparsion):
  parent = generate_binary(D)
  parent_fitness = problem(parent)

  for iter in range(Niter):
    child = mutation(parent)


  child_fitness = problem(child)

  if comparsion(child_fitness, parent_fitness):
    parent = child
    parent_fitness = child_fitness

  return parent, parent_fitness

x, y = hillclimber(500, onemax, 10, generate_binary, binary_mutation, greater_than_equal)
print(f"Best Solution: {x}, fitness: {y}")

def sphere(x):
  return (x**2).sum()

def generate_continuous(D):

  return np.random.randint(-3, 3, D)
    
    
  for i in range(5):
    x = generate_continuous(3)
    y = sphere(x)
    print(f"Solution {x}, fitness {y}")

def additive_gaussian(parent):
  z = np.random.randn() * 0.1
  idx = np.random.randint(parent.shape[0])
  child = parent.copy()
  child[idx] = parent[idx] + z
  return child

def less_than_equal(a, b):
  return a <= b 

x, y = hillclimber(500, sphere, 10, generate_continuous, additive_gaussian, less_than_equal)
print(f"Solution x: {x}, fitness {y}")

[ 7  5 10  8  3  3  4 10  7 10] + 67
[ 8  0  7  6  2  4  5  5 10  7] + 54
[9 8 9 2 9 6 5 5 1 7] + 61
[10  8 10  7  4  0  7  6 10  8] + 70
[2 7 3 2 5 9 3 9 5 0] + 45


### 2.2 – Algorithm implementation

In [ ]:
def ruinAndRecreate(iterations):
    
    RandList = []
    
    bestRoute = randRoute(distances)
    bestRouteLength = route_length(bestRoute, distances)
    
    for i in range(iterations):
        route2 = randRoute(distances)
        print(route2)
        routelength2 = route_length(route2, distances)
        if routelength2 < bestRouteLength:
            bestRouteLength = routelength2
            bestRoute = route2
        RandList.append(bestRouteLength) #iterates through and generates a new route , if it was better than previous routes it becomes the best route is kept till the next iteration 
    return RandList
#print(ruinAndRecreate(30))

###  2.3 – Visualisation of results

In [ ]:
def results():
    SwapList = []
    RuinNRecreateList = []
    
    for i in range(30):
        SwapList.append(swap(30))
        RuinNRecreateList.append(ruinAndRecreate(30))
        
        # turning both lists into numpy arrays because it works out max , min and average calculations
        Array1 = numpy.array(SwapList) 
        Array2 = numpy.array(RuinNRecreateList)

    plt.plot(Array1.min(axis=0))
    plt.plot(Array1.max(axis=0))
    plt.plot(Array1.mean(axis=0))
    
    plt.plot(Array2.min(axis=0))
    plt.plot(Array2.max(axis=0))
    plt.plot(Array2.mean(axis=0))
    plt.legend(["Swap mutation minimum","Swap mutation maximum", "Swap mutation mean", "Ruin and Recreate minimum", "Ruin and Recreate maximum", "Ruin and Recreate mean"], loc=(1,0.5))
    plt.show()
    
results()